name = "troves-and-coves"
main = "server/cloudflare-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Ultra-lightweight free tier configuration
[env.production]
name = "troves-and-coves-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
# Create with: wrangler kv:namespace create "CACHE"
id = "your-kv-namespace-id"

[vars]
ENVIRONMENT = "production"

# No build step needed for lightweight worker
[build]
command = "echo 'Lightweight worker - no build required'"