name = "troves-and-coves"
main = "server/cloudflare-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Optimized for 1 vCPU and 512MB RAM constraints
[env.production]
name = "troves-and-coves-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
# Create with: wrangler kv:namespace create "CACHE"
id = "your-kv-namespace-id"

[vars]
ENVIRONMENT = "production"
MEMORY_LIMIT = "384"
CPU_LIMIT = "1"

# Memory-optimized build
[build]
command = "npm run build"