name: Deploy to GitHub Pages and Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages-cloudflare"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job for React frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
        env:
          NODE_ENV: production
          VITE_API_URL: https://troves-coves-api.reverb256.workers.dev
          VITE_GITHUB_PAGES_URL: https://reverb256.github.io/trovesandcoves
          VITE_CLOUDFLARE_ANALYTICS: ${{ secrets.CLOUDFLARE_ANALYTICS_TOKEN }}
          VITE_ENABLE_HTTPS: true
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/public'

  # Deploy to GitHub Pages
  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Deploy Cloudflare Worker
  deploy-cloudflare-worker:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # Setup Cloudflare KV namespaces
  setup-kv-namespaces:
    runs-on: ubuntu-latest
    needs: deploy-cloudflare-worker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create PRODUCTS_KV namespace
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: kv:namespace create "PRODUCTS_KV" --preview false
        continue-on-error: true
      
      - name: Create CART_KV namespace
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: kv:namespace create "CART_KV" --preview false
        continue-on-error: true
      
      - name: Create ANALYTICS_KV namespace
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: kv:namespace create "ANALYTICS_KV" --preview false
        continue-on-error: true
      
      - name: Create TROVES_CACHE namespace
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: kv:namespace create "TROVES_CACHE" --preview false
        continue-on-error: true
